name: Quality Checks

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    quality:
        name: Code Quality & Tests
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Check formatting
              run: pnpm run format:check

            - name: Run linter
              run: pnpm run lint

            - name: Type check
              run: pnpm run typecheck

            - name: Run tests
              run: pnpm run test

            - name: Run tests with coverage
              run: pnpm run test:coverage

            - name: Upload coverage reports
              uses: actions/upload-artifact@v4
              if: success()
              with:
                  name: coverage-reports
                  path: |
                      coverage/
                      !coverage/tmp/
                  retention-days: 30

    build:
        name: Build Check
        runs-on: ubuntu-latest
        needs: quality

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build project
              run: pnpm run build

            - name: Check build output
              run: |
                  if [ ! -f "dist/index.js" ]; then
                    echo "Build failed: dist/index.js not found"
                    exit 1
                  fi
                  echo "Build successful: dist/index.js created"
